modLoader = "kotlinforforge"
loaderVersion = "[5.8,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "unfocused"
version = "${version}"
displayName = "Unfocused"
authors = "SSBlur"
description = '''
Blur's library mod, it just has a lot of useful common code.
'''
logoFile = "icon.png"

[[dependencies.unfocused]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unfocused]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "unfocused.mixins.json"

[[mixins]]
config = "unfocused-common.mixins.json"
